### ISSUE TITLE
curl demo URL sanity check

### ISSUE THREAD

**Issue by clach04** [ActianCorp/OpenROAD_json#3]
Doing testing with @durwinwright and https://github.com/ActianCorp/OpenROAD_json/tree/master/curl#curl-example-for-existing-comtest-application lists two different applications:

* jsonrpcservertest  
* comtest 

is comtest supposed to have helloworld and subtract?

https://github.com/ActianCorp/OpenROAD_json/blob/39b2c095ba0483c40f1c3d9797c9bc953296b07c/curl/README.md?plain=1#L21

https://github.com/ActianCorp/OpenROAD_json/blob/39b2c095ba0483c40f1c3d9797c9bc953296b07c/curl/README.md?plain=1#L49

multiple instances, just showing the two diffs above.

**Comment by clach04** [comment]
Looping in @sawantprasad

**Comment by bodob** [comment]
@clach04, comtest application does not contain subtract procedure.
The two examples you mention are for different tests - several tests are using subtract contained in the jsonrpcservertest application, others are using the helloworld procedure contained in comtest.

BTW, the URLs used should be changed to use the new format using the "app" parameter rather the subcontext.
E.g. instead of `http://HOSTNAME:PORT/openroad/comtest` the URL should look like `http://HOSTNAME:PORT/openroad/jsonrpc?app=comtest`

**Comment by clach04** [comment]
Resolved by https://github.com/ActianCorp/OpenROAD_json/commit/4b13f6828f67e0eeb0b02bc22cc81611d8da587c which just got merged. Closed after discussion with @sawantprasad
